services:
    nginxwebdav:
        container_name: nginxwebdav
        build:
            context: .
        volumes:
            - ./data:/data
            - ./config:/config
            # - ./custom-cont-init.d:/custom-cont-init.d # optional: additional cont-init.d-scripts like multi-user support
        environment:
            - PUID=33  # www-data
            - PGID=33  # www-data
            - TZ=America/New_York
            - SERVER_NAMES=localhost
            - TIMEOUTS_S=1200 # these are seconds
            - CLIENT_MAX_BODY_SIZE=1G # must end with M(egabytes) or G(igabytes)
        ports:
            - 32080:80
